---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moetify-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moetify-app
  template:
    metadata:
      labels:
        app: moetify-app
    spec:
      containers:
        - name: moetify-app
          image: kakugirai/moetify:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
          env:
            - name: APP_REDIS_ADDR
              value: "redis-master:6379"